### ISSUE TITLE
DependenciesSchemaParser fails on multiline input

### ISSUE THREAD

**Issue by paulortman** [dependencies-io/cli#61]
### Description
The DependenciesSchemaParser is not capable of parsing multiline json.

### What I Did
This fails:
```python
print('<Dependencies>{}</Dependencies>'.format(json.dumps(lockfile_output, indetn=2))) 
```

This works
```python
print('<Dependencies>{}</Dependencies>'.format(json.dumps(lockfile_output)))
```

**Comment by davegaeddert** [comment]
Should be fixed now with 0ad93761a66fe31d1995df7c1e23fee06c9bf45c (https://github.com/dependencies-io/schema/commit/bbbfe8c53934b7da8459f1a6d6f483c2fd312ad8)
